model = "gpt-5.3-codex"
model_reasoning_effort = "high"

suppress_unstable_features_warning = true

model_auto_compact_token_limit = 100000

[sandbox_workspace_write]
network_access = true

[shell_environment_policy]
exclude = [
  "*PASSWORD*",
  "*PASS*",
  "*SECRET*",
  "*TOKEN*",
  "*API_KEY*",
  "*ACCESS_KEY*",
  "*PRIVATE_KEY*",
  "*SIGNING_KEY*",
  "*ENCRYPT*",
  "*CIPHER*",
  "*DSN*",
  "*SALT*",
  "*HASH*",
  "AWS_*",
  "AZURE_*",
  "GCP_*",
  "GCPOGLE_*",
  "GOOGLE_*",
  "OPENAI_*",
  "STRIPE_*",
  "SENTRY_*",
  "SENDGRID_*",
  "TWILIO_*",
  "PAYPAL_*",
]

[features]
rmcp_client = true

[mcp_servers.laravel-boost]
command = "php"
args = ["artisan", "boost:mcp"]
startup_timeout_sec = 120.0
tool_timeout_sec = 120.0

[mcp_servers.chrome-devtools]
command = "/mnt/c/Windows/System32/cmd.exe"
args = ["/c", "npx.cmd", "-y", "chrome-devtools-mcp@latest", '--executablePath=C:\Program Files\Google\Chrome\Application\chrome.exe', "--isolated"]
startup_timeout_sec = 30.0
tool_timeout_sec = 300.0

[mcp_servers.figma]
url = "https://mcp.figma.com/mcp"

[mcp_servers.linear]
url = "https://mcp.linear.app/mcp"

[mcp_servers.sentry]
url = "https://mcp.sentry.dev/mcp"
